### ISSUE TITLE
sh: 1: Syntax error: Bad fd number

### ISSUE THREAD

**Issue by mictadlo** [jkimlab/mySyntenyPortal#13]
Hi,
I ran `/mySyntenyPortal/mySyntenyPortal build -p 24 -conf labVSTobVSTom.conf` but I got the following errors and warings:

```
Building a website...
##### Read a configuration file #####
 - /QRISdata/Q0231/mysytenyportal/labVSTobVSTom.conf
 => Input data type: Assembly

##### Alignment #####
 - Lab-Tobacco near
 - Lab-Tomato near
 - Tobacco-Tomato near

##### Building synteny blocks #####
 - Lab-Tobacco 1000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
 - Lab-Tobacco 3000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
 - Lab-Tobacco 5000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
 - Lab-Tomato 1000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
 - Lab-Tomato 3000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
 - Lab-Tomato 5000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
 - Tobacco-Lab 1000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
 - Tobacco-Lab 3000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
 - Tobacco-Lab 5000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
 - Tobacco-Tomato 1000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
 - Tobacco-Tomato 3000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
 - Tobacco-Tomato 5000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
 - Tomato-Lab 1000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
 - Tomato-Lab 3000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
 - Tomato-Lab 5000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
 - Tomato-Tobacco 1000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
 - Tomato-Tobacco 3000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
 - Tomato-Tobacco 5000
sh: 1: Syntax error: Bad fd number
make: Warning: File 'Makefile' has modification time 5.9 s in the future
make: warning:  Clock skew detected.  Your build may be incomplete.
    => No synteny blocks
```
What did I miss?

Thank you in advance,

Michal

**Comment by devenderarora** [comment]
Is this fix?

**Comment by jongin333** [comment]
Hi, mictadlo and devenderarora,

I'm sorry for the late response.
This problem, which was occurred at ubuntu, has been fixed.
So, try again, please.

Thank you,
Jongin

**Comment by devenderarora** [comment]
Dear jongin333, I tried this but ended up with the same result.
sh: 1: Syntax error: Bad fd number.

I followed perl mySyntenyPortal build ./configurations/example/config.conf

**Comment by devenderarora** [comment]
Dear jongin333, 
While I was trying to install the master copy downloaded from github it ended up with some installation issue but when I am using the conventional way of 
git clone https://github.com/jkimlab/mySyntenyPortal.git
cd mySyntenyPortal
perl ./install.pl build
sudo perl ./install.pl install
it is installing well and leads to the error when running the above mention command.
 Is their any issue in installing from github repository?

**Comment by jongin333** [comment]
Dear devenderarora,

mySyntenyPortal was tested in Ubuntu16, 18 and CentOS6 (based on bash shell environment).
And now it works well in my case.

Do you use any other OS or system?

Thanks,
Jongin

**Comment by devenderarora** [comment]
Thank You for the response and fixing the error. I am working in Ubuntu server and running the example data first. Now the error is removed but I am not able to reproduce the svg or png files for the example data. 
I am getting an error in Human-Mouse alignment
Use of uninitialized value $ref_fa in concatenation (.) or string at /path/build_mySyntenyPortal.pl line 177.
Use of uninitialized value $tar_fa in concatenation (.) or string at /path/build_mySyntenyPortal.pl line 177.
Use of uninitialized value $_[0] in substitution (s///) at /usr/share/.../.../Basename.pm line 180
fileparse(): need a valid pathname at /path/build_mySyntenyPortal.pl line 182.
Is there anything I am doing wrong?
Thankyou for your patience.

**Comment by jongin333** [comment]
Dear devenderarora,

The example configuration files are written by using the relative paths of data files.
So, you can run in the configuration directory (example code below).

cd /mySyntenyPortal_path/configurations
../mySyntenyPortal build -conf ./examples/example.assembly.conf

Thanks,
Jongin

**Comment by devenderarora** [comment]
I reinstalled and followed exact same script to run example data but ended up with the same error. 

Use of uninitialized value $ref_fa in concatenation (.) or string at /path/build_mySyntenyPortal.pl line 177.
Use of uninitialized value $tar_fa in concatenation (.) or string at /path/build_mySyntenyPortal.pl line 177.
Use of uninitialized value $_[0] in substitution (s///) at /usr/share/.../.../Basename.pm line 180
fileparse(): need a valid pathname at /path/build_mySyntenyPortal.pl line 182.

**Comment by jongin333** [comment]
Dear devenderarora,

The example configuration files in examples directory were not updated.
So, I deleted them.

You can try using sample2.conf for building mySyntenyPortal with some assemblies.
cd /mySyntenyPortal_path/configurations
../mySyntenyPortal build -conf ./sample2.conf

Jongin

**Comment by devenderarora** [comment]
Dear Jongin,
Thankyou so much for your prompt response. Now it works well. 
Highly appreciate your help.

**Comment by jongin333** [comment]
Dear devenderarora,

I'm glad to hear that.
Good luck to you.

Thank you,
Jongin
