### ISSUE TITLE
documentation on how to create the input files 

### ISSUE THREAD

**Issue by mictadlo** [jkimlab/mySyntenyPortal#3]
Hi,
Do you have any documentation on how to create the input files?

Thank you in advance,

Michal

**Comment by jongin333** [comment]
Hi, Michal.

I already explained the input files and parameters for building mySyntenyPortal in README.
What do you mean the input files?
How to build assemblies (or synteny blocks) with your own data or how to build a parameter file of mySyntenyPortal?

Thank you,
Jongin

**Comment by mictadlo** [comment]
Hi Jongin,
Looking at the two cytoband files it appears that some of the columns are not required:

- https://github.com/jkimlab/mySyntenyPortal/blob/master/data/example_inputs/cow.cytoband
- https://github.com/jkimlab/mySyntenyPortal/blob/master/data/example_inputs/mouse.cytoband

Which columns are required and do you have a script on how to create the above files?

Thank you in advance.

Michal

**Comment by jongin333** [comment]
Hi Michal, 

I downloaded the cytoband information files using the Table Browser in UCSC genome browser (https://genome.ucsc.edu/cgi-bin/hgTables). Unfortunately, I don't have a script for making cytoband information file.

The cytoband files are Tab-separated files. Although the fourth column (name) is not important to visualize plots, the number of columns of cytoband file cannot be changed (chrom  chromStart  chromEnd  name  gieStain).

Thank you,
Jongin
