### ISSUE TITLE
lastz aligment as parameter

### ISSUE THREAD

**Issue by mictadlo** [jkimlab/mySyntenyPortal#4]
Hi,
Would it be possible to add lastz alignment as a parameter to mySyntenyPortal in order to run lastz on a cluster because our cluster does not have apache?

Thank you in advance.

Best wishes,

Michal

**Comment by jongin333** [comment]
Hi, Michal.

Do you want to perform the pairwise alignment using mySyntenyPortal pipeline?
Then, you can do this by only building (compile) mySyntenyPortal (following the steps below).

1. Build (compile) mySyntenyPortal source code
   $ ./install.pl build

2. Build your alignments and synteny blocks using mySyntenyPortal pipeline
   $ ./mySyntenyPortal build -p [number of threads] -conf [your configuration file]

Then, the results of alignment and synteny blocks are in data directory ( [mySyntenyPortal path]/data/[project name])

Thank you,
Jongin
