### ISSUE TITLE
Resolutions

### ISSUE THREAD

**Issue by mictadlo** [jkimlab/mySyntenyPortal#8]
Hi,
I have two assemblies which I would like to compare. Could you please explain how to set up the resolutions?

```
   # Resolutions (REQUIRED)
   # The minimum size of synteny blocks in base pair
      >Resolutions
      150000,300000,400000,500000
```

Thank you in advance,

Michal

**Comment by jongin333** [comment]
Hi, Michal

The resolution is set for the minimum size of the synteny blocks.

For example,
The larger resolution makes the large size synteny blocks. The small alignments or gaps which are smaller than the resolution can be ignored in the process of building synteny blocks.

In other words, the larger resolution builds high-level syntenic relationships. In contrast, the smaller resolution builds high-resolution synteny blocks which contain small size alignments and gaps but it can be complex to show and have some false-positive information.

Thank you,

Jongin
